### ISSUE TITLE
상품 전체 조회 -> price가 감싸진것, 좋아요와 조회 수 요구

### ISSUE THREAD

**Issue by MangDic** [JeonGoo/JeonGoo_Server#22]
상품 전체 조회 -> price가 감싸진것, 좋아요와 조회 수 요구

**Comment by BangKiHyun** [comment]
- [x] price가 VO로 감싸져 있어서 발생. 감싸지 않고 넘기도록 수정
- [ ] 관심 상품 도메인 구현 후 좋아요 수 return 하도록 수정
- [x] 조회 컬럼 추가한 후 넘겨주도록 수정, 상세페이지 조회 API 추가
